language: csharp
solution: MonoAGS.sln

matrix:
  include: 
    - os: linux
      mono: latest
      env: BUILD_CONFIG=DesktopRelease BUILD_PLATFORM="Any CPU"
      sudo: required
      dist: trusty
    - os: osx
      mono: latest
      env: BUILD_CONFIG=DesktopRelease BUILD_PLATFORM="Any CPU"
 
install:
  - wget https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/install.sh
  - chmod +x install.sh
  - ./install.sh -c beta 
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
 - dotnet restore
 - nuget restore MonoAGS.sln
 - xbuild /p:Configuration=$BUILD_CONFIG /p:Platform="$BUILD_PLATFORM" MonoAGS.sln
 - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Source/Tests/bin/Release/Tests.dll